site_name: Sistema de Auditoria Jurídica S.A.C.
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: pt
          default: true
          name: Português
          build: true
        - locale: en
          name: English
          build: true

nav:
  - Início / Home: index.md
  - Arquitetura / Architecture: arquitetura.md
  - Referência / Reference: referencia.md